### ISSUE TITLE
Documentation unclear

### ISSUE THREAD

**Issue by volkanunsal** [skymethod/denoflare#1]
Hi. I'm interested in using this project, but the documentation puzzles me. There is no clear path from installation to running and deploying a worker. 

Why do I need to define my projects in the `.denoconfig` file in the home folder? Isn't it more intuitive to create a config file at the root of the project?

**Comment by johnspurlock-skymethod** [comment]
Hi there - Denoflare is still in the early stages of development, but I'll try to help you get started.

After [installing denoflare via deno install](https://denoflare.dev/cli/#installation), you should be able to run a worker locally using `denoflare serve`:
```sh
$ denoflare serve /path/to/your/worker.ts
```

The [configuration](https://denoflare.dev/cli/configuration) is used when you start getting more complicated, like setting env vars, or creating multiple configurations for a given worker script.  By default, it will look for configuration in `cwd` or any ancestors, or you can specify it with the `--config` option.

Personally, I find it useful to keep all of my script configurations in a single `.denoflare` configuration file (this way you can share auth) in a common ancestor, so in my case the home dir works well.

Right now the config file may have secrets (deployment script name, env var values, auth tokens, local port numbers) so if you keep it in your project you'll probably want to exclude it from source control.

**Comment by marshallswain** [comment]
It took me a few minutes to figure out the API, as well.  It's really quite flexible and clean.  I've opened a PR that adds a `Guides` section to the documentation.  It includes a guide on getting up and running quickly with `denoflare serve`. 

https://github.com/skymethod/denoflare-docs/pull/1

**Comment by marshallswain** [comment]
I noticed that the current documentation shows absolute paths, but I found that I was able to use relative paths.  I'm on a Mac and I'm unsure if it could be different on another platform.

**Comment by johnspurlock-skymethod** [comment]
Relative paths should work again as of v0.3.2, see #2 for the gory details.  I'm on Mac as well, but he was on Windows and verified relative paths work over there too.
