### ISSUE TITLE
How are worker sites (i.e. static assets) handled by Denoflare?

### ISSUE THREAD

**Issue by da99** [skymethod/denoflare#10]
Does Denoflare support Workers Sites (ie publishing static assets alongside a workers script)?

**Comment by johnspurlock-skymethod** [comment]
Sites was built as a workaround before [Cloudflare Pages](https://pages.cloudflare.com/), it is just a client-side script in Wrangler that publishes local assets to KV.

For almost all use cases where sites was used, Pages is much better as it exists today.

Denoflare does not try to recreate the old Sites Wrangler script, but you could push to KV yourself via the CF REST API, or our wrapper cli command: `denoflare cfapi put-key-value`.

For truly static content (zero-latency, bundled into the uploaded script), you can use the new `importText` and `importBinary` introduced in [Release 0.4.2](https://github.com/skymethod/denoflare/releases).  This uses Cloudflare's magic import syntax under the hood when pushing to CF.

Hope that helps!

**Comment by da99** [comment]
Thanks very much. That answers everything. 😊

**Comment by SimonEast** [comment]
Thanks for this. I was just trying to work out how to achieve this, and after following your tip and a bit of trial and error I got it working locally with this code.

```
import { importText } from 'https://raw.githubusercontent.com/skymethod/denoflare/v0.5.9/common/import_text.ts'

// Load some static text from a file
const text = await importText(import.meta.url, './test.txt');

export default {
    async fetch(request: Request, env: any) {
        let url: URL = new URL(request.url);
        if (url.pathname == '/text')
            return new Response(text);

        // ...
    },
}
```

Just wanted to post in case it helps anyone else. Perhaps a simple example like this could be included in the docs somewhere?

I assume it would work very similarly for `importBinary`, except that you'd need to specify the correct MIME type in the `new Response(...)`.
