### ISSUE TITLE
Deno dependency management not working yet

### ISSUE THREAD

**Issue by chris-carrington** [skymethod/denoflare#15]
Thank you for this lovely code!

I am following this link https://examples.deno.land/dependency-management & it is not working yet, any idea why please?!
<img width="1306" alt="index-ts" src="https://user-images.githubusercontent.com/5852440/169600257-f51ddb4f-87c7-40eb-b94f-c84b3ea6af02.png">

<img width="1309" alt="deps-ts" src="https://user-images.githubusercontent.com/5852440/169600137-f206c52a-e1d3-48a3-9eb7-f8c034a5b9aa.png">

**Comment by johnspurlock-skymethod** [comment]
In deps.ts, you should either
```ts
export * from "./peace/isolates/isCurrentRoute.ts"
```
to make all symbols available, or
```ts
export { isCurrentRoute } from "./peace/isolates/isCurrentRoute.ts"
```
to make only one or more specific symbols available

Then your import on line 3 of index.ts should work

**Comment by chris-carrington** [comment]
Thank you so much! I tried both methods & it is not working yet

isCurrentRoute.ts

```
export default (path: string, request: Request) => {
  return new URLPattern({ pathname: path }).test(request.url)
}
```

Here is the error with export *
<img width="1298" alt="export-star" src="https://user-images.githubusercontent.com/5852440/169604484-630102c7-f8f5-4e12-9698-dbde7c421f01.png">

Here is the error with export brackets
<img width="1298" alt="export-bracket" src="https://user-images.githubusercontent.com/5852440/169604547-345dee2c-f0fd-4b02-b07f-2e134665e9cf.png">

**Comment by chris-carrington** [comment]
I see Deno is built on Rust, and Cloudflare Workers has lovely Rust support, so I am learning Rust now & do not need to figure this out. Thank you so much!
