### ISSUE TITLE
Passing in environment variables into .denoflare

### ISSUE THREAD

**Issue by janat08** [skymethod/denoflare#23]
how to Passing in environment variables into .denoflare

**Comment by johnspurlock-skymethod** [comment]
Do you mean using local environment variables as substitutions in the [denoflare config file](https://denoflare.dev/cli/configuration)?

There is no way to do this at the moment, although this is a good idea - do you have a syntax you suggest for embedding them into the json config value strings?  Denoflare already has two convenience variables: `${localPort}` and `${pushId}`, so my first thought for env would be something like `${env.VAR}`

Another thing that might work for you in the meantime - any command line arguments you pass to `push` or `serve` should override what's specified in the config, so you could pass local env var values that way.

**Comment by janat08** [comment]
I meant I don't want to pass in my cloudflare credentials.

**Comment by johnspurlock-skymethod** [comment]
If you don't define a profile in config, denoflare will look for `CF_ACCOUNT_ID` and `CF_API_TOKEN` env vars as a fallback.  Does that work for you?

https://github.com/skymethod/denoflare/blob/8cae83699a4f9d2ddce7698c4bb0abc0540e9358/cli/config_loader.ts#L27

**Comment by janat08** [comment]
I haven't tried it as it's not in docs.

**Comment by johnspurlock-skymethod** [comment]
Good point - just added to https://denoflare.dev/cli/configuration

<img width="974" alt="image" src="https://user-images.githubusercontent.com/47259736/182667634-398cdbc4-ac65-4ebc-b960-121fdbdc2629.png">

I still like the idea of env var support in any config value string though - would work here and useful for passing build-time bindings as well.

**Comment by janat08** [comment]
I was hoping that deno could be used to tap into nodejs packages, but I got
deno is not defined errors when tried using firebase-auth which uses xml
and fetch. I also tried adding polyfill from deno. Do i have the right
idea, deno is about making nodejs work on fetch?

**Comment by johnspurlock-skymethod** [comment]
Not sure exactly what you mean.

Cloudflare Workers [runtime](https://developers.cloudflare.com/workers/runtime-apis/) does not support any nodejs builtins or Deno builtins

Denoflare (this project) is a way to author worker scripts in Deno, which are then bundled and pushed to Cloudflare.

Obviously you cannot use any Deno namespace or builtins in your scripts when running on CF (and therefore `denoflare serve` as well) unless you stub them out.

Deno's nodejs experimental support is a feature of the Deno runtime, which is not available on Cloudflare Workers.

Note you can still use many npm packages in Denoflare by importing them from https://esm.sh

**Comment by john-tmc** [comment]
@johnspurlock-skymethod any progress in using something like ${env.VAR} ? I'm planning to just make a bash script to search & replace the value, if there's no plan yet. (I'm open to forking the current `cli/config_loader.ts` to add this mod if allowed).  I prefer to keep my secrets, a secret :)  and the value configurable to environment file, for CI/CD purposes. (need to store planetscale, upstash, etc credentials)

Thanks!

**Comment by johnspurlock-skymethod** [comment]
@john-tmc, do you mean in the .denoflare file?  

You can pass env vars as bindings via the cli in environments like dev or CI, see the --x-binding parameters in [push](https://denoflare.dev/cli/push)

**Comment by johnspurlock-skymethod** [comment]
Was able to squeeze this into the most recent release!
https://github.com/skymethod/denoflare/releases/tag/v0.5.12

Use `${env:VAR_NAME}` as substitutions in binding or profile config objects

**Comment by john-tmc** [comment]
@johnspurlock-skymethod Awesome! Just in time, thanks!

**Comment by ninxadev** [comment]
Quick note regarding the fallback env vars `CF_ACCOUNT_ID` and `CF_API_TOKEN`:

Cloudflare [deprecated both of these](https://developers.cloudflare.com/workers/wrangler/system-environment-variables/) in Wrangler v3, so might be good to replace/add the new ones: `CLOUDFLARE_ACCOUNT_ID` & `CLOUDFLARE_API_TOKEN`

**Comment by johnspurlock-skymethod** [comment]
Thanks for the heads up @ninxadev - added in https://github.com/skymethod/denoflare/commit/dd160cccea8f3fab197355c7057d93803739eecf
