### ISSUE TITLE
canot serve example 

### ISSUE THREAD

**Issue by bobwatcherx** [skymethod/denoflare#25]
i follow you tutorial https://denoflare.dev/guides/serve
and i serve project
but get error message

Error running script Error: Bad module.default: undefined
    at Function.create (blob:null/748eb05c-fe5c-4070-a880-9bcb5cfeae9b:573:49)
    at async Function.start (blob:null/748eb05c-fe5c-4070-a880-9bcb5cfeae9b:672:50)
    at async blob:null/748eb05c-fe5c-4070-a880-9bcb5cfeae9b:2504:22
    at async RpcChannel.receiveMessage (blob:null/748eb05c-fe5c-4070-a880-9bcb5cfeae9b:39:36)
    at async self.onmessage (blob:null/748eb05c-fe5c-4070-a880-9bcb5cfeae9b:2532:13)

my .denoflare file
```
{
    "$schema": "https://raw.githubusercontent.com/skymethod/denoflare/v0.5.7/common/config.schema.json",
    "scripts": {
        "hello-local": {
            "path": "main.ts",
            "localPort": 3030
        }
    },
    "profiles": {
        "account1": {
            // your cloudflare account id
            "accountId": "6b9a6f27ffddd42d8f9b0f16d655e7fe",
            // your cloudflare api token
            "apiToken": "CxRhXkwP35y0rKm5fjJ2_eIiWjkalz8Z8t7Pb-yE"
        }
    }
}
```

**Comment by johnspurlock-skymethod** [comment]
Hmm, assuming your main.ts looks similar to the structure from that guide example, I'm thinking it might be due to your config `"path"` being non-absolute.  Right now the path needs to be an absolute file path or a url.

From the schema docs:
```
Local file path, or https: url to a module-based worker entry point .ts, or a non-module-based worker bundled .js
```

Change the path to an absolute path and let me know if that fixes it for you.


Also if those are your production `accountId` and `apiToken`, you should rotate them immediately.

AccountId is ok to be leaked, but not apiToken

**Comment by johnspurlock-skymethod** [comment]
Did you figure this out?

**Comment by bobwatcherx** [comment]
I Will try later

**Comment by augustblack** [comment]
fwiw, I had a similar issue and it took me a while to figure it out.
I was about to write here, when I did figure it out.

coming from using typescript in node with various bundlers, I'm used to importing like so:

```
import { Something. } from './module'
```

however, with deno you need to have the .ts at the end like:

```
import { Something. } from './module.ts'
```

once I found the file that was importing without the full '.ts' path the error went away.
