### ISSUE TITLE
Worker type definitions?

### ISSUE THREAD

**Issue by ylxdzsw** [skymethod/denoflare#29]
I'm trying denoflare for cf worker development and having issues with the type definitions. The [official type definition file](https://www.npmjs.com/package/@cloudflare/workers-types) does not play with deno as it contains many conflicting definitions.

I have found [this file](https://github.com/skymethod/denoflare/blob/master/common/cloudflare_workers_types.d.ts) in the repo but it seems to be different from the official definitions. For example, the `get` method of `KVNamespace` can be used with only 1 argument but raises type error when using the definition from this file.

I wonder what's the recommended / common practice here. Thanks.

**Comment by JustinGrote** [comment]
So using the "official" Cloudflare types is blocked on https://github.com/cloudflare/workers-types/issues/199

until they fix how they present things, we're stuck with our own bespoke types. I've been working on some new well-documented types for the module worker syntax for my own use, which is a lot easier to encapsulate things than with the "globals" syntax, but yeah right now it's a bit painful.

**Comment by johnspurlock-skymethod** [comment]
Yea I've been maintaining my own types (in that cloudflare_workers_types.d.ts) from back before the official types file even existed.

Still find it useful as the the official one lags behind (esp for new cf alpha/beta services) and doesn't play nice with Deno.

I would like to have cloudflare_workers_types.d.ts reflect the current cloudflare production runtime as much as possible, so if you know of any specific differences that you are relying on in production, please raise them as issues/PRs on that file.  Only thing to keep in mind is that denoflare's fakes/stubs/proxies may need to change along with any core type changes.

**Comment by johnspurlock-skymethod** [comment]
@ylxdzsw The latest [release v0.5.10](https://github.com/skymethod/denoflare/releases/tag/v0.5.10) allows the no-options version of `KVNamespace.get`.  There are still advantages to maintaining a Deno-friendly and forward-looking version of these types, so our `cloudflare_workers_types.d.ts` isn't going anywhere any time soon.

**Comment by JustinGrote** [comment]
For anyone following, the @cloudflare/workers-types was updated so that it is now partially importable to avoid the conflicts that used to occur. I haven't tested it with denoflare but it may be easier to use at least a subset of the types now since they dont have to be global and things like "blob" should no longer conflict.

**Comment by JustinGrote** [comment]
To follow up, I tested and this works great using unpkg:

```
import { Request, ExecutionContext } from "https://unpkg.com/@cloudflare/workers-types@4.20221111.1/experimental/index.ts"
import * as semVer from "https://deno.land/std@0.167.0/semver/mod.ts";

export default {
	async fetch() {
		const res = `Hello World! ${semVer.increment("1.2.3", "patch")}`
		console.log(res)
		return new Response(res);
	},
};
```

**Comment by johnspurlock-skymethod** [comment]
Nice, I could see migrating over to these piecemeal (re-exporting) in our types file where duplicative, and just keeping our file for the bleeding edge services that are not in workers-types yet.

I gave them some feedback about better jsdocs, and they are working on it.  That's another advantage our types still have in some cases.
