### ISSUE TITLE
Config Json schema does not propose `ServiceBinding`

### ISSUE THREAD

**Issue by halimt92** [skymethod/denoflare#32]
When creating the denoflare configuration while referring to the schema `https://raw.githubusercontent.com/skymethod/denoflare/v0.5.10/common/config.schema.json` suggested in the denoflare configuration (https://denoflare.dev/cli/configuration), we cannot bind a service to our configuration in the `bindings` section. The only options proposed are in the image attached.

Is there something we are missing in order to bind a worker to another service?

<img width="531" alt="image" src="https://user-images.githubusercontent.com/48407395/201916531-a77f131d-cc4f-473a-8a84-b89db2684a01.png">

**Comment by johnspurlock-skymethod** [comment]
Let's see - it looks like service bindings are supported as command-line options in [`serve`](https://denoflare.dev/cli/serve) and [`push`](https://denoflare.dev/cli/push), but not supported in the JSON config.

IIRC, I added those service bindings quite a while ago, before service bindings were even public to investigate them on Cloudflare.  I could add them to the JSON config for pushing to Cloudflare, but simulating them locally in `serve` seems like more work.

**Comment by halimt92** [comment]
That is what we thought looking at the codebase. We are mainly using denoflare for deployment though and so we added the service bindings via the cli arguments directly to avoid the config.json limitation. We wanted to mention it for you guys, since it is stated in the documentation but is not applicable.

**Comment by johnspurlock-skymethod** [comment]
Thanks! I have other goodies to get into the codebase before I cut another release tag.  But since Deno is so flexible in terms of running from any git pointer you should be ok with running from a commit hash in the meantime.
