### ISSUE TITLE
Denoflare using importMaps from deno.json

### ISSUE THREAD

**Issue by thebergamo** [skymethod/denoflare#52]
While I'm trying to execute my code in Denoflare, it is always complaining about my imports that have reference to the importMaps as it is recommended in Deno. Is there any config to make sure the importMaps are getting used while running denoflare?

**Comment by thebergamo** [comment]
I see that my issue is a duplicate of #30, maybe we can restart conversation about this?

**Comment by johnspurlock-skymethod** [comment]
ok - i've reopened that one.

Can you comment over there if importMaps is the only thing you need out of deno.json/jsonc ?  And just basically what need from it.

Denoflare was around long before import maps and deno.json were a thing in Deno, or even desired : )
