### ISSUE TITLE
Cannot use Async fetch prototype like Cloudflare allows

### ISSUE THREAD

**Issue by riderx** [skymethod/denoflare#61]
Here is the code who produce the error:
`error: Uncaught (in promise) Error: putScript failed: status=400, errors=10068 The uploaded script has no registered event handlers.`

```
export default {
  async fetch(request: Request): Promise<Response> {
    // fake await to simulate a slow response
    await new Promise(resolve => setTimeout(resolve, 1000))
    return new Response('Hello, world!')
  },
}
```

The code without async work at upload.
The code with async work in Cloudflare workers, so it should be allowed in Denoflare.

**Comment by johnspurlock-skymethod** [comment]
News to me, every single one of my denoflare works has async fetch, including the denoflare examples.

Take a look, for example: https://github.com/skymethod/denoflare/blob/master/examples/keyspace-worker/worker.ts

From the error message, it sounds like you are using the old "service worker" event handler type, which really no one should be using these days (Denoflare was created a long time ago when this was the only option!)

**Comment by riderx** [comment]
@johnspurlock-skymethod thanks for showing the way.

just changing the proto to:
```
export default {
  async fetch(request: Request, env: any, context: any): Promise<Response> {
    // fake await to simulate a slow response
    await new Promise(resolve => setTimeout(resolve, 1000))
    return new Response('Hello, world!')
  },
}
```
Made it work, I was following the tutorial here:
https://docs.deno.com/runtime/manual/advanced/deploying_deno/cloudflare_workers
who use the old proto it seems.
I can see in the official doc here the env is present:
https://denoflare.dev/guides/serve

Thanks a lot for showing the way !

**Comment by johnspurlock-skymethod** [comment]
Great! glad you got it working
