### ISSUE TITLE
Deprecated --unstable flag warning

### ISSUE THREAD

**Issue by mattvr** [skymethod/denoflare#67]
The documentation says to install with `--unstable`, but as of Deno 1.40 this now results in a warning upon each use.

```
The `--unstable` flag is deprecated and will be removed in Deno 2.0. Use granular `--unstable-*` flags instead.
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags
```

I installed without `--unstable` and it seems to be working OK, which unstable features are used exactly? Couldn't determine in a quick perusal. (Deno reference and available flags here: https://docs.deno.com/runtime/manual/tools/unstable_flags)

**Comment by johnspurlock-skymethod** [comment]
Hmm, yes it appears the Deno team deprecated `--unstable` in 1.40.

At a minimum, you'll need [--unstable-worker-options](https://docs.deno.com/runtime/manual/tools/unstable_flags#--unstable-worker-options) to run `serve` in the default mode (permissionless isolate for sandboxing and hot-reloading)

**Comment by johnspurlock-skymethod** [comment]
Updated docs in https://github.com/skymethod/denoflare-docs/commit/377539a0552f67ab438f8c305cea5198e515031d
