### ISSUE TITLE
DenoflareResponse.statusText not implemented

### ISSUE THREAD

**Issue by nounderline** [skymethod/denoflare#70]
It's impossible to use `Response.statusText` as it's not implemented:

https://github.com/skymethod/denoflare/blob/75ac0717ec34f1ed500c3605ef068394646a7486/common/denoflare_response.ts#L75C2-L81C6

**Comment by nounderline** [comment]
I think it's safe to return an empty string as per https://developer.mozilla.org/en-US/docs/Web/API/Response/statusText

**Comment by johnspurlock-skymethod** [comment]
I can plumb it through rpc like the others - curious if you were using it explicitly or just enumerating through all response properties

**Comment by nounderline** [comment]
I used it for error logging, like this:

https://github.com/worker-tools/router/blob/5e5a96b33178567c535f99644522e562f1a55947/index.ts#L142C1-L149C4

**Comment by johnspurlock-skymethod** [comment]
Ok, made it available as of a284d0f9730c38b662acda6fe4692ac22f7c176d
