### ISSUE TITLE
response.headers.getSetCookie is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by tbmale** [skymethod/denoflare#74]
When I'm using the code at [https://codeberg.org/tbmale/afraidlogin]( https://codeberg.org/tbmale/afraidlogin) deployed to cloudflare, with denoflare, I get an error in cloudflare :

*login_response.headers.getSetCookie is not a function or its return value is not iterable*

The same code deployed with wrangler works.

**Comment by johnspurlock-skymethod** [comment]
It looks Cloudflare only gained that method last year [1].

You'll need to set the compatibility date for that worker to on or after that date (`2023-03-01`)

[1] https://developers.cloudflare.com/workers/configuration/compatibility-dates/#headers-supports-getsetcookie

**Comment by tbmale** [comment]
@johnspurlock-skymethod, thank you, that was it !

**Comment by johnspurlock-skymethod** [comment]
Great!  Glad you got it working
